# Puerto de la aplicación
server.port=8080

# Nombre de la aplicación
spring.application.name=bookiin-backend

# Configuración de Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/bookiin_db
spring.datasource.username=bookiin_user
spring.datasource.password=bookiin_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Cors (Para la PWA)
# En producción reemplazar '*' por la URL del frontend en Vercel
cors.allowed-origins=*

# Google Books API Base URL
google.books.api.url=https://www.googleapis.com/books/v1/volumes
